### PR TITLE
ci: add setup process of dynamic link benchmarking to avoid runing out of gas

### PR DESCRIPTION
**Pull request by loloicci**
# Description
This PR is to avoid the error https://github.com/line/cosmwasm/actions/runs/3359799506/jobs/5568655612

## Types of changes

- [ ] Bug fix (changes which fixes an issue)
- [ ] New feature (changes which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] ETC (build, ci, docs, perf, refactor, style, test)

## Checklist

- [x] I followed the [contributing guidelines](https://github.com/line/cosmwasm/blob/main/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly. (not needed)
- [ ] I have added tests to cover my changes. (not needed)
- [x] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

### CODE REVIEW

**Comment by da1suk8** [comment]
I tried `cargo bench --no-default-features --features bench -- --color never --save-baseline singlepass` and I got this error.
Is it related to environment error?

```
$pwd
~/cosmwasm/packages/vm
$cargo bench --no-default-features --features bench -- --color never --save-baseline singlepass
Benchmarking DynamicLink/native_dynamic_link_trampoline with dummy contract_call
Benchmarking DynamicLink/native_dynamic_link_trampoline with dummy contract_call: Warming up for 3.0000 s
Benchmarking DynamicLink/native_dynamic_link_trampoline with dummy contract_call: Collecting 12 samples in estimated 10.000 s (12M iterations)
Benchmarking DynamicLink/native_dynamic_link_trampoline with dummy contract_call: Analyzing
DynamicLink/native_dynamic_link_trampoline with dummy contract_call
                        time:   [839.67 ns 848.11 ns 853.57 ns]
                        change: [-35.259% -26.509% -16.533%] (p = 0.00 < 0.05)
                        Performance has improved.
Benchmarking DynamicLink/native_dynamic_link_trampoline with mock cache environment
Benchmarking DynamicLink/native_dynamic_link_trampoline with mock cache environment: Warming up for 3.0000 s
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeErr { msg: "Wasmer runtime error: RuntimeError: unreachable" }', packages/vm/benches/main.rs:286:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by loloicci** [comment]
In my local environment, no error is issued.

```
$ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.57.0 (f1edd0429 2021-11-29)`

$ sysctl machdep.cpu.brand_string
machdep.cpu.brand_string: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
```

**Comment by shiki-tak** [comment]
LGTM except for errors that occur only in M1.
If the problem is resolved, we will approve it.

**Review by zemyblue — COMMENTED** [review]
I think it is another problem. But when I do test in local (Apple M1Pro), the below error was occurred.
```
$ cargo bench --no-default-features --features bench -- --color never --save-baseline singlepass

...

error[E0046]: not all trait items implemented, missing: `range`
  --> packages/storage/src/prefixed_storage.rs:46:1
   |
46 | impl<'a> Storage for PrefixedStorage<'a> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `range` in implementation
   |
   = help: implement the missing item: `fn range(&'a self, _: std::option::Option<&[u8]>, _: std::option::Option<&[u8]>, _: Order) -> Box<(dyn Iterator<Item = (Vec<u8>, Vec<u8>)> + 'a)> { todo!() }`

error[E0046]: not all trait items implemented, missing: `range`
  --> packages/storage/src/prefixed_storage.rs:95:1
   |
95 | impl<'a> Storage for ReadonlyPrefixedStorage<'a> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `range` in implementation
   |
   = help: implement the missing item: `fn range(&'a self, _: std::option::Option<&[u8]>, _: std::option::Option<&[u8]>, _: Order) -> Box<(dyn Iterator<Item = (Vec<u8>, Vec<u8>)> + 'a)> { todo!() }`

For more information about this error, try `rustc --explain E0046`.
error: could not compile `cosmwasm-storage` due to 2 previous errors
```

**Review by shiki-tak — APPROVED** [review]
If the problem unresolved, please merge after create issue.

**Review by zemyblue — APPROVED** [review]

**Review by da1suk8 — APPROVED** [review]
I made https://github.com/line/cosmwasm/issues/258

**Pull request merged**
