### PR TITLE
ci: add ci tests for package derive

### LINKED ISSUE #228: Add ci test for package derive

### PR DESCRIPTION
**Pull request by loloicci**
# Description

Closes #228

## Types of changes

- [ ] Bug fix (changes which fixes an issue)
- [ ] New feature (changes which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] ETC (build, ci, docs, perf, refactor, style, test)

## Checklist

- [x] I followed the [contributing guidelines](https://github.com/line/cosmwasm/blob/main/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly. (Not needed)
- [ ] I have added tests to cover my changes. (Not needed)
- [x] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

### CODE REVIEW

**Review by da1suk8 — COMMENTED** [review]
It looks the same as #230 except for the version difference, but what is the reason for distinguishing it from #230 ?

Is this a PR to check the effect of the version difference?

**Comment by loloicci** [comment]
> It looks the same as https://github.com/line/cosmwasm/pull/230 except for the version difference, but what is the reason for distinguishing it from https://github.com/line/cosmwasm/pull/230 ?

This PR is for main branch and #230 is for dynamic_link branch. I think both branches need the same ci tests before merging one into another one, and I make 2 PRs.

**Comment by da1suk8** [comment]
Sorry, I didn't check it properly. Thank you.

**Review by da1suk8 — APPROVED** [review]

**Review by shiki-tak — APPROVED** [review]
LGTM

**Pull request merged**
